/**
 * CSS Custom Properties Adapter
 *
 * Generates a :root CSS file with all design tokens as custom properties.
 */

import * as fs from 'fs';
import * as path from 'path';
import { DesignData } from './reader';
import { rgbToHex, parsePx, classifyFont, buildSpacingMap, buildRadiusMap } from './utils';

export interface CSSVariablesOptions {
  outputDir: string;
  filename?: string;
  prefix?: string; // e.g., "ds" → --ds-color-primary
}

export function generateCSSVariables(data: DesignData, opts: CSSVariablesOptions): string {
  const p = opts.prefix ? `${opts.prefix}-` : '';
  const lines: string[] = [];

  lines.push(`/* Design Tokens — extracted from ${data.sourceUrl || 'unknown'} */`);
  lines.push(`/* Generated by design-system-extractor */`);
  lines.push('');
  lines.push(':root {');

  // ── Colors ──
  lines.push('  /* ── Colors ── */');

  if (data.colors.primary?.value) {
    lines.push(`  --${p}color-primary: ${rgbToHex(data.colors.primary.value)};`);
  }
  if (data.colors.secondary?.value) {
    lines.push(`  --${p}color-secondary: ${rgbToHex(data.colors.secondary.value)};`);
  }
  if (data.colors.accent?.value) {
    lines.push(`  --${p}color-accent: ${rgbToHex(data.colors.accent.value)};`);
  }

  for (const [shade, token] of Object.entries(data.colors.neutral)) {
    lines.push(`  --${p}color-neutral-${shade}: ${rgbToHex(token.value)};`);
  }

  for (const [name, token] of Object.entries(data.colors.semantic)) {
    if (token.value) {
      lines.push(`  --${p}color-${name}: ${rgbToHex(token.value)};`);
    }
  }

  for (const [name, token] of Object.entries(data.colors.overlays)) {
    // Keep rgba for overlays (alpha matters)
    lines.push(`  --${p}color-overlay-${kebab(name)}: ${token.value};`);
  }

  // ── Typography ──
  lines.push('');
  lines.push('  /* ── Typography ── */');

  const SEMANTIC_FONT_KEYS: Record<string, string> = {
    primary: 'sans', body: 'sans', heading: 'heading', display: 'display',
    mono: 'mono', code: 'mono', system: 'system', serif: 'serif',
  };
  const usedFontKeys = new Set<string>();
  for (const family of data.typography.fontFamilies) {
    let key = SEMANTIC_FONT_KEYS[family.name.toLowerCase()] || classifyFont(family.name);
    if (usedFontKeys.has(key)) key = `${key}-${usedFontKeys.size}`;
    usedFontKeys.add(key);
    lines.push(`  --${p}font-${key}: ${family.stack};`);
  }

  // Font sizes (deduplicated)
  const seenSizes = new Set<string>();
  const sizeNames = ['xs', 'sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl', '7xl', '8xl', '9xl'];
  let sizeIdx = 0;
  for (const s of data.typography.scale) {
    if (seenSizes.has(s.size)) continue;
    seenSizes.add(s.size);
    const name = sizeIdx < sizeNames.length ? sizeNames[sizeIdx] : `size-${Math.round(parsePx(s.size))}`;
    lines.push(`  --${p}font-size-${name}: ${s.size};`);
    sizeIdx++;
  }

  // Font weights
  const weightNames: Record<number, string> = {
    100: 'thin', 200: 'extralight', 300: 'light', 400: 'normal',
    500: 'medium', 600: 'semibold', 700: 'bold', 800: 'extrabold', 900: 'black',
  };
  for (const w of data.typography.weights) {
    const name = weightNames[w] || `w-${w}`;
    lines.push(`  --${p}font-weight-${name}: ${w};`);
  }

  // Line heights
  for (let i = 0; i < data.typography.lineHeights.length; i++) {
    const lh = data.typography.lineHeights[i];
    lines.push(`  --${p}line-height-${i + 1}: ${lh};`);
  }

  // ── Spacing ──
  lines.push('');
  lines.push('  /* ── Spacing ── */');

  const spacingMap = buildSpacingMap(data.spacing.scale);
  for (const [key, val] of Object.entries(spacingMap)) {
    lines.push(`  --${p}space-${key.replace('.', '-')}: ${val};`);
  }

  // ── Border Radius ──
  lines.push('');
  lines.push('  /* ── Border Radius ── */');

  const radiusMap = buildRadiusMap(data.borderRadius);
  for (const [key, val] of Object.entries(radiusMap)) {
    const cssKey = key === 'DEFAULT' ? 'default' : key;
    lines.push(`  --${p}radius-${cssKey}: ${val};`);
  }

  // ── Shadows ──
  if (data.shadows.length > 0) {
    lines.push('');
    lines.push('  /* ── Shadows ── */');
    for (const shadow of data.shadows) {
      lines.push(`  --${p}shadow-${kebab(shadow.name)}: ${shadow.value};`);
    }
  }

  // ── Transitions ──
  if (data.transitions.durations.length > 0 || data.transitions.timingFunctions.length > 0) {
    lines.push('');
    lines.push('  /* ── Transitions ── */');

    const durationNames = ['fastest', 'fast', 'normal', 'slow', 'slower', 'slowest'];
    const sortedDurations = [...data.transitions.durations].sort((a, b) => parsePx(a) - parsePx(b));
    for (let i = 0; i < sortedDurations.length; i++) {
      const name = i < durationNames.length ? durationNames[i] : `d-${i}`;
      lines.push(`  --${p}duration-${name}: ${sortedDurations[i]};`);
    }

    for (let i = 0; i < data.transitions.timingFunctions.length; i++) {
      const tf = data.transitions.timingFunctions[i];
      const name = tf === 'ease' ? 'default' : tf === 'ease-out' ? 'out' : tf === 'ease-in' ? 'in' : tf === 'linear' ? 'linear' : `ease-${i}`;
      lines.push(`  --${p}ease-${name}: ${tf};`);
    }
  }

  // ── Z-Index ──
  if (data.zIndex.length > 0) {
    lines.push('');
    lines.push('  /* ── Z-Index ── */');
    for (const z of data.zIndex) {
      lines.push(`  --${p}z-${z.value}: ${z.value};`);
    }
  }

  // ── Breakpoints (reference) ──
  if (Object.keys(data.breakpoints).length > 0) {
    lines.push('');
    lines.push('  /* ── Breakpoints (reference — use in @media) ── */');
    for (const [name, bp] of Object.entries(data.breakpoints)) {
      const val = bp.min || bp.max || bp.value;
      if (val) lines.push(`  --${p}breakpoint-${name}: ${val};`);
    }
  }

  lines.push('}');
  lines.push('');

  const css = lines.join('\n');
  const outputPath = path.join(opts.outputDir, opts.filename || 'design-tokens.css');
  fs.mkdirSync(opts.outputDir, { recursive: true });
  fs.writeFileSync(outputPath, css);

  return outputPath;
}

function kebab(str: string): string {
  return str.replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, '');
}
